apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hello-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World - PRODUCTION</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; margin: 50px; background-color: #f0fff0; }
            h1 { color: #228b22; }
            .env { background-color: #90ee90; padding: 10px; border-radius: 5px; }
        </style>
    </head>
    <body>
        <h1>Hello World - Production</h1>
        <p>Simple nginx test application running in Kubernetes</p>
        <div class="env">Environment: <strong>PRODUCTION</strong></div>
        <p><small>Production environment - stable and monitored</small></p>
    </body>
    </html>
