# Kustomization overlay for production environment
# Applies production-specific patches with higher resource allocations
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# Strategic merge patches for production environment optimizations
patchesStrategicMerge:
  - deployment-patch.yaml  # Increases replicas and resources for production
  - configmap-patch.yaml   # Production-specific HTML content

# Environment-specific labels
commonLabels:
  environment: prod
