apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hello-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World - DEV</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; margin: 50px; background-color: #f0f8ff; }
            h1 { color: #1e90ff; }
            .env { background-color: #87ceeb; padding: 10px; border-radius: 5px; }
        </style>
    </head>
    <body>
        <h1>Hello World - Development</h1>
        <p>Simple nginx test application running in Kubernetes</p>
        <div class="env">Environment: <strong>DEV</strong></div>
        <p><small>Development environment - expect changes and instability</small></p>
    </body>
    </html>
