# ConfigMap containing HTML content for nginx
# This serves as the main page content for the hello-nginx application
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hello-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; margin: 50px; }
            h1 { color: #333; }
        </style>
    </head>
    <body>
        <h1>Hello World</h1>
        <p>Simple nginx test application running in Kubernetes</p>
        <p>Environment: <span id="env">BASE</span></p>
    </body>
    </html>
