# Kustomization base configuration for hello-nginx
# Defines the base resources and common labels for the application
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: hello-nginx
  app.kubernetes.io/version: "1.0"
  app.kubernetes.io/component: web
