# Service for hello-nginx application
# Provides internal cluster access to the nginx pods
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespace: hello-nginx
  labels:
    app: hello-nginx
spec:
  type: ClusterIP  # Internal access only - use ingress for external access
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hello-nginx
