# Deployment patch for staging environment
# Increases replicas and resource limits for staging workload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: hello-nginx
spec:
  replicas: 2  # Higher replica count for staging availability
  template:
    spec:
      containers:
      - name: nginx
        resources:
          requests:  # Increased baseline resources
            memory: "128Mi"
            cpu: "100m"
          limits:    # Higher limits for staging environment
            memory: "256Mi"
            cpu: "200m"
